#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Blog
  include ::Thrift::Struct, ::Thrift::Struct_Union
  URL = 1
  CONTENT = 2

  FIELDS = {
    URL => {:type => ::Thrift::Types::STRING, :name => 'url'},
    CONTENT => {:type => ::Thrift::Types::STRING, :name => 'content'}
  }

  def struct_fields; FIELDS; end

  def validate
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field url is unset!') unless @url
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field content is unset!') unless @content
  end

  ::Thrift::Struct.generate_accessors self
end

